### ISSUE TITLE
How to start it? Add this info to Readme?

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/XiSearch#10]
Sorry, if this seems too trivial, but how do you start the search engine and point it at the database?

**Comment by colin-combe** [comment]
This is a stupid comment. I can see it in the code.

**Comment by lutzfischer** [comment]
there are several ways - one is via a integrated gui - one via just starting it as a commandline-tool and tell it the database connection and search id via command line

**Comment by colin-combe** [comment]
Thanks Lutz, I hadn't seen the usage instruction it prints out. (I closed the issue when I saw them)

**Comment by colin-combe** [comment]
> unless we have the required database schema public as well - there is no point in pointing these out

The database schema is public now, so its worth pointing these out.
