### ISSUE TITLE
Restarting the searches

### ISSUE THREAD

**Issue by llmlrnr** [Rappsilber-Laboratory/XiSearch#105]
Hello,

Many thanks for the great software and the detailed project description!

I am using XiSearch on a linux cluster and run out of available computing time when performing very complex searches. Is there a way to restart a search that was cancelled at some point or the only way to make it work is to restrict the search space as much as possible?

**Comment by lutzfischer** [comment]
Not directly - the best I could suggest is to filter the peaklist to only contain spectra without result. xiSEACH even comes with a tool for that.
```
java -cp /path/to/xiSearch.jar rappsilber.gui.localapplication.ScanFilter
```

you could load the search result into the third tab (ScanFilter) and select "Exclude Selected". On the first tab you give your original mgf file and a path to a new one and press run.

**Comment by lutzfischer** [comment]
How many variable modifications are you searching?

**Comment by lutzfischer** [comment]
unless your crosslinker is reacting to cystein you probably set cysteine-carbamidomethylation as fixed - and  even then other ways would be better - like having an additional crosslinker that is carbamidomethylation-lighter then the actuall crosslinker and links to  cysteine-carbamidomethylation.

Long run time could also come from lag of memory. If you can try to give it more memory

**Comment by grandrea** [comment]
If i can suggest- put your modifications and crosslinker modifications as
variable linear, rather than full variable, it will help memory quite a bit.

You can drop the noncovalent, especially if you used in sourcd
fragmentation, but it can lead to false positive identifications.

**Comment by grandrea** [comment]
Hi,
Yes you can use msconvert for this (subset by time or scan event), or simply write a script using pyteomics pyhton package to split the mgf files (chatgpt4 knows the pyteomics syntax quite well). you can then use the scripts in the hpc_scripts to run in parallel on a cluster (or whatever script you like of course!) and then combine_searches.py or the like to recombine the results.
