### ISSUE TITLE
Variable modifications on crosslinked peptides

### ISSUE THREAD

**Issue by llmlrnr** [Rappsilber-Laboratory/XiSearch#118]
What is the correct way to specify a variable modification that should only be present on an aminoacid modified with the crosslinker (e.g. oxidation)?

Specifying it via modification:variable will lead to unnecessary increased search space, but using the MODIFICATIONS word inside of the crosslinker definition will define a variable modification on both cross-linked and linear peptides modified with the crosslinker, correct?

Is is possible to only consider the variable modification on the crosslinked peptides?

**Comment by grandrea** [comment]
yes, the modification word will define it on both peptide pairs and linear peptides modified with the crosslinker.

 I am not aware of a feature directly doing what you are requesting, sorry. If I understand correctly, you should be able to to achieve it by defining your main crosslinker as usual. Then, include a second line with an additional crosslinker incorporating the mass of the crosslinker and the modificaiton, and then not specifying any MODIFICATIONS for that crosslinker. Let me know if that works!
