### ISSUE TITLE
Entering alternative crosslinkers into the GUI

### ISSUE THREAD

**Issue by dnz01** [Rappsilber-Laboratory/XiSearch#120]
I want to search some data with TBDSPP (tBu-PhoX). Can this crosslinker:(crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:[tBuPhoX];MASS:[209.97181];LINKEDAMINOACIDS:[K(0),S(0.2),T(0.2),Y(0.2)];MODIFICATIONS:[331.21575];LINEARMODIFICATIONS:[331.21575];LOSSES:[list];STUBS:[list]
Be added to the GUI so that I can just click on it in the crosslinkers drop-down menu?

Thanks

**Comment by lutzfischer** [comment]
You can added to the BasicConfigEntries.conf file that comes with xiSEARCH. 
There is a section for crosslinkers and any that are defined there are shown in the interface.

**Comment by lutzfischer** [comment]
https://github.com/Rappsilber-Laboratory/XiSearch?tab=readme-ov-file#changing-or-adding-new-entries-to-the-graphical-config-interface
