### ISSUE TITLE
is there a recommended java version for xiSearch?

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/XiSearch#2]
question in subject heading... thats all.

c

**Comment by lutzfischer** [comment]
currently the development is running on 8 but I try to keep things compatible with 7 as well - not always remember this as issue #4 shows. Is there any point to go to an earlier version of java?

**Comment by colin-combe** [comment]
no point going to earlier version that i can see... Will close this and #4

On 10 Jan 2017 13:15, "Lutz Fischer" <notifications@github.com> wrote:

currently the development is running on 8 but I try to keep things
compatible with 7 as well - not always remember this as issue #4
<https://github.com/Rappsilber-Laboratory/XiSearch/issues/4> shows. Is
there any point to go to an earlier version of java?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rappsilber-Laboratory/XiSearch/issues/2#issuecomment-271572462>,
or mute the thread

**Comment by lutzfischer** [comment]
Conclusion: 
currently 1.8 is suggested
1.7 compatibility is wished for

**Comment by colin-combe** [comment]
I not sure 1.7 is even wished for...
