### ISSUE TITLE
how to create bmps in the configuration file of Xisearch as an heterofunctional and asymetric crosslinker 

### ISSUE THREAD

**Issue by ljavier2401** [Rappsilber-Laboratory/XiSearch#28]
Hi,
I would like to use XiSearch to do quantitative crosslinking experiments but I have find a problem with the definition for a BMPS crosslinker.
It is s non-symmetric cross-linker reagent, it is also a heterofunctional cross-linker reagent and it reacts with Cys and primary amino groups (both with the N-terminal of the protein and Lys epsilon amino group). It does not react with two Lysine residues, neither with two Cys residues at the same time.
The following proposal is appropriated?
crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:BMPS;MASS:153.0426;FIRSTLINKEDAMINOACIDS:C;SECONDLINKEDAMINOACIDS:K,nterm
Please would you help me how to define bmps?
Waiting for your kind help.

**Comment by lutzfischer** [comment]
**`crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:BMPS;MASS:X.XXX;FIRSTLINKEDAMINOACIDS:C;SECONDLINKEDAMINOACIDS:K,nterm`**

Defines a linker that links C to K or C to protein n-terminal.
So yes that would be ok. Possibly you could define it as 
**`crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:BMPS;MASS:X.XXX;FIRSTLINKEDAMINOACIDS:C;SECONDLINKEDAMINOACIDS:K,S,T,Y,nterm`**
As the ester group should be able to link these as well. 
On a short check I suspect that the mass is actually wrong - I get [C7 O3 N1 H5]  = **`151.026943`** (linked BMPS minus one displaced hydrogen on the lysine). But I am not a chemist so maybe get that cross-checked by somebody else.

If you would want to search also for links between K and K additionally (not for this cross-linker but as an theoretical example) it would be
**`crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:StrangeCrossLinker;MASS:X.XXX;FIRSTLINKEDAMINOACIDS:C,K;SECONDLINKEDAMINOACIDS:K,S,T,Y,nterm`**
that would permit C to K, K to K, C to nterm and K to nterm but *no* K to C.

**Comment by ljavier2401** [comment]
Thank you very much for your help and advices.

Best regards,
Javier
