### ISSUE TITLE
what are correct columns for scan number in csv files generated by xiFDR?

### ISSUE THREAD

**Issue by ljavier2401** [Rappsilber-Laboratory/XiSearch#29]
Dear Prof Rappsilber and colleagues, 

I am trying to follow the instructions you described in the manuscript you published in Nature protocols for performing quantitative crosslinking mass spectrometry. 
I have already used with success XiSearch and xiFDR.
Now I am trying to filter the csv files for the identified regular and cross-linked peptides in order to generate the corresponding *.ssl file to be uploaded by Skyline.
The format of *.ssl file very simple, a tab separated values with only four columns filename, scan, charge and peptide sequence.
However, when I opened csv files, saved by xiFDR, for linear peptides and cross-linked peptides I noticed that there is two different scan numbers for each identification one is named as "scan" and the other as "scanID".
What ids the correct one that I have to include in the *.ssl files? I want to be sure before to proceed further.

best regards, 
javier

**Comment by lutzfischer** [comment]
Scan - is the scan-number as reported by the masspec (actually as parsed out from the TITLE field in the mgf-file/apl-file). The scanid is the index of that scan in the file.
E.g. the first scan in an mgf file will have 1 as scanid but most likely a much larger scan_number (scan)

**Comment by lutzfischer** [comment]
sorry just noticed I explained what is the difference but not what to use. What you want for skyline is the scan-column - as that references back to the scan in the raw file while scanid reference the position in the peaklist file.
