### ISSUE TITLE
Doesn't build. Error on src/rappsilber/utils/PermArray.java:127 

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/XiSearch#4]
```
src/rappsilber/utils/PermArray.java:127: error: <anonymous rappsilber.utils.PermArray$1> is not abstract and does not override abstract method remove() in Iterator
        return new Iterator<T[]>() {
```

Commit https://github.com/colin-combe/XiSearch/commit/8a4b9f3d4acc1d6551299aa14841726f27e1dd7b adds a quick hacky fix.

pull request #3 will would bring this in as well now I think

**Comment by lutzfischer** [comment]
seems like in version 8 of java there is a default implementation for remove() in iterable - not sure how that works as it is an interface. But at least it was not complaining about the missing method.
Anyway now it exists - I bassically did take over @colin-combe change - just not sure how to do a partial pull request - so "reimplemented" the solution
