### ISSUE TITLE
Use of EDC as XL (zero/-18 mass spacer?)

### ISSUE THREAD

**Issue by Alemarcohen** [Rappsilber-Laboratory/XiSearch#42]
My name is Alex Cohen, I run the Proteomics Core Facility at Dalhousie University in Nova Scotia Canada. I have XL project I need to work on, unfortunately, ProteomeDiscoverer and the current Xlink nodes (which we have) do not work with our samples. Briefly, EDC (https://www.thermofisher.com/order/catalog/product/22980) was used to link to proteins (I have the Fastas). This is a -no spacer- XL that couples -NH3 (Nt and K) with -COOH (Ct and D/E residues). I just downloaded XiSearch from your website and exploring the GUI. Could you help me define the XL command please?

This is what I have come up with so far:
 
crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:EDC;MASS:0;FIRSTLINKEDAMINOACIDS:K(0),nterm(0);SECONDLINKEDAMINOACIDS:D(0),E(0),cterm(0)
 
Any feedback is greatly appreciated!

Quick follow-up: I’m under the impression that reaction mechanism of EDC between to proteins actually generates an amide bond, with the loss of H2O, so I wonder if the XL mass could be set to a negative value (-18.0105642)?

**Comment by lutzfischer** [comment]
your right the mass should be -18
what we use is:
```
crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:EDC;MASS:-18.0105647;FIRSTLINKEDAMINOACIDS:E,D,cterm;SECONDLINKEDAMINOACIDS:K,S,Y,T,nterm
```
You can leave out the (0)

**Comment by Alemarcohen** [comment]
Thanks Lutz!
Quick question: I notice you have: :K,S,Y,T and nt as reactive groups. According the Thermo, the reactions is: "• Reaction target: activates carboxyl groups to conjugate to amino groups (primary amines)"
Have you actually seen side reactions to S, Y and T with this reagent in your hands/samples? Or just being respectable with organic chemistry?
Cheers!
Alex

**Comment by lutzfischer** [comment]
I personally haven't looked specifically into this for EDC. But part of the EDC chemistry is that it forms an active ester and should therefore be comparable to BS3/DSS in that respect. And for BS3 we do see side reactions occurring in quite noticeable amounts. 

I just had a look at some random EDC search I found here (not my search so take this with a grain of salt) 

Residue(s) | Occurences(in_unique_links)
-- | --
E-K | 178 
D-K | 79   
E-S | 40 
E-T | 37 
D-T | 21  
E-Y | 19  
D-S | 15 

Part of these will be wrong site assignment (i.e. K just beside a Y) and you can try to counter that by setting a penality  to the side reactions (set the specificity to something like K(0),S(0.2),T(0.2),Y(0.2),nterm(0)) - BUT on heterodimeric crosslinker this is currently not completely supported. You can test it and see what you get.

**Comment by Alemarcohen** [comment]
Thanks! I'll keep you posted with what we encounter with our samples.

**Comment by lutzfischer** [comment]
transferred the infos to the "wiki"
