### ISSUE TITLE
Two protein experiments - Config/FDR settings?

### ISSUE THREAD

**Issue by Alemarcohen** [Rappsilber-Laboratory/XiSearch#44]
Hi Xi team!

Quick question. I'm working on a project trying to find xlinks between two proteins which have been expressed and purified from ecoli. The SDS-PAGE bands suggest the two proteins are close to >95% pure. 
I tried running Xi workflow (XiSearch, XiFDR and XiView) using just the two proteins in the Fasta file and the FDR parameters in the tutorial. So far, so good. When I upload the data to XiView I get quite a few XLs, however, inspecting the spectra I have a strong feeling that I have overfit my data (very few and low abundance peaks matched to the theoretical Y and B fragments).
Do you have any suggestions for this kind of samples in terms of FDR parameters?

Thanks!!! we are making huge strides on our data!

Alex

**Comment by lutzfischer** [comment]
(removed the link from your message - sorry I wanted you to send it to my email-address not to github - as that is public - and not sure if you want to have the data public at the moment)
I had a quick look at the run and the FDR is probably not very reliable. You have only 16 links identified. That means the FDR is very much under-defined. Also that you have 21 Target-Decoy and 21 Decoy-Decoy matches is odd (as in more decoys then target links). By formula (FDR = (TD-DD)/TT)  that gives 0 but it is totally against expectations. These kind of things always makes me mistrust the result. 

Also you have very oddly high charge states (>= 20) and I am not sure if xi will handle these correctly (no experience with something like that). I think you should filter these out before doing the FDR-analysis (if you can I would suggest to remove them also from peaklist before searching with xiSearch).
Actually I wonder if that is somewhat an artefact of the raw-file to mgf conversion. Looking at scatter plot (View->Scatterplot) and there at charge states I see that you have either charge states below 8 (more in line with expectations) or >= 20 (strange).

Also the spectra look odd, e.g. when looking at some example spectra and looking at the quality plots it looks like your fragment errors don't behave as expected - they spread out evenly through the error range - but should cluster towards 0. You have some extremely rich spectra (as in to many peaks). 

First of all I would not do an FDR on unique links. You just don't have enough data to make a valid statement about the FDR on level of unique links. At the moment that FDR could be anywhere between 0 (what is calculated) and something like 20% or more (my bet would be on it being rather larger then smaller).

As you search just two proteins I would also tell xiFDR to ignore groups - the splitting in self-links and between links will be less helpful here and make each group even more underdefined in terms of FDR.
 
Also is there a specific reason to have non-tryptic digest? 

Maybe you can email me directly (lutz[dot]fischer[at]tu[minus]berlin[dot]de) if you want to discus things less public.  

Actually seeing the data and scores I feel that this does not look like a xiSEARCH result (which would be fine - but I can say less about what could go wrong then).

**Comment by Alemarcohen** [comment]
Lutz, I DID perform a linear search using ProteomeDiscoverer and the
correct proteins were identified, even using the CRAP DB as a background
DB. So I know both my bait proteins ARE there.
Alex

**Comment by lutzfischer** [comment]
Yes I know you identified the two proteins - it is more of a question what else you identified. Unless your two proteins are the two very most abundant proteins in the sample - with a large margin in terms of abundance - it might make sense to include other proteins identified in the cross-link search as well.
