### ISSUE TITLE
loop-links?

### ISSUE THREAD

**Issue by ThomasGossenreiter** [Rappsilber-Laboratory/XiSearch#47]
Hello,
is there a way to set loop-links for BS3?

Best,
Thomas

**Comment by lutzfischer** [comment]
at the moment xiSEARCH does not search specifically for loop-links. But you can add the cross-linker mass as a variable modification on one residue - I.e. a stand-in for a loop link.

**Comment by ThomasGossenreiter** [comment]
Okay, thank you for the information and the quick response!
