### ISSUE TITLE
Strange error related to netbeans build process (Ant related?)

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/XiSearch#5]
Doesn't build for me in netbeans because it says:
```
/home/colin/XiSearch/nbproject/build-impl.xml:868: taskdef class org.netbeans.modules.java.j2seproject.copylibstask.CopyLibs cannot be found
 using the classloader AntClassLoader[]
```

**Comment by lutzfischer** [comment]
Should be fixed now. Not 100% sure why that jar file has to be there - it should actually come from netbeans - but hey it fixes the problem

**Comment by colin-combe** [comment]
Probably I'm using a different version of netbeans. We could specify netbeans version.

Compiling XiSearch is totally working for me now. Thanks.

**Comment by lutzfischer** [comment]
it was actually broken when I checked it out as well. I excluded all the jar-files from being checked into git (via .gitignore) and somehow netbeans appears to need one jar file - the copylib one - even so it is originally a copy from netbeans-library folder...
