### ISSUE TITLE
.ssl file not accepted by Skyline

### ISSUE THREAD

**Issue by derffff2022** [Rappsilber-Laboratory/XiSearch#61]
Dear XiSearch team,
I was recently working on a crosslinker quantitation project based on BS3.  However, recently I am facing a problem before quantifying my data on Skyline. I was following your Nature Protocol article (https://doi.org/10.1038/s41596-018-0089-3) and it seems like the manual generation of .ssl file from csv is not recognized by the Skyline. I posted the question on Skyline forum yesterday and they said columns named "File" and "Scan" is missing. I also tried to use the automatic generation tool on xiView but it is not responding as well. Previously I also tried plink2 and XlinkX and I noticed the csv file format is very different therefore incompatible with your developed tools. I am wondering if you have any suggestions and recommendation to overcome this dilemma.

I would very grateful towards your precious ideas and help!

Best Regards,
Peter

**Comment by colin-combe** [comment]
Hi Peter,

Yes, the .ssl export from xiVIEW is broken - actually that menu option was meant to be removed but snuck back in by mistake. It is removed now and will be reinstated if/when fixed.

There is another open issue about .ssl export from xiVIEW - https://github.com/Rappsilber-Laboratory/xiView_container/issues/73#issuecomment-721788958

In it @chambm described a new format added Skyline to represent crosslinked peptides and asked:

> Do you think we could unify on this representation?

I would be happy to unify on that representation, its just not something I've got around to doing yet. (I don't know if @chambm is still out there interested in this, he didn't recieve a response from me back in 2020.)

**Comment by lutzfischer** [comment]
xiSEARCH actually comes with a little util to translate your results into a skyline ssl-file. Not in the format described  [in the above mentioned comment](https://github.com/Rappsilber-Laboratory/xiView_container/issues/73#issuecomment-721788958) but closer to the one described in the paper.

To run that you can 
```
java -cp [path to the xiSEARCH.jar] rappsilber.gui.skyline.Xi2Skyline
```
you can then select the CSM file and the search config and generate an ssl file. I know that somebody just got it to read with skyline - not sure what version of skyline though. Can have a look at getting the "new" format implemented. Looks to be simpler than what what I have. In my export the crosslinker is encoded as a modified lysine and the crosslink-sites are encoded as +H modifications.

**Comment by derffff2022** [comment]
> xiSEARCH actually comes with a little util to translate your results into a skyline ssl-file. Not in the format described [in the above mentioned comment](https://github.com/Rappsilber-Laboratory/xiView_container/issues/73#issuecomment-721788958) but closer to the one described in the paper.
> 
> To run that you can
> 
> ```
> java -cp [path to the xiSEARCH.jar] rappsilber.gui.skyline.Xi2Skyline
> ```
> 
> you can then select the CSM file and the search config and generate an ssl file. I know that somebody just got it to read with skyline - not sure what version of skyline though. Can have a look at getting the "new" format implemented. Looks to be simpler than what what I have. In my export the crosslinker is encoded as a modified lysine and the crosslink-sites are encoded as +H modifications.

Thank you very much! This library is finally built successfully
