### ISSUE TITLE
Add DSPP/PhoX configuration

### ISSUE THREAD

**Issue by anfoss** [Rappsilber-Laboratory/XiSearch#68]
I want to add a new cross linker (PhoX). This is what I added to the conf so far but I am not sure it is correct/the best way to do it.

```

crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:PhoX;MASS:209.97181;LINKEDAMINOACIDS:K(0),S(0.2),T(0.2),Y(0.2),nterm(0)

modification:linear::SYMBOLEXT:phoxOH;MODIFIED:K,S,T,Y;DELTAMASS:227.98237
modification:linear::SYMBOLEXT:phoxNh;MODIFIED:K,S,T,Y;DELTAMASS:226.99836

```

However, I get extremely low nr of cross linking compared to other softwares for exactly the same sample. Is there any other parameter which should be added/modified?

**Comment by lutzfischer** [comment]
The crosslinker definition looks alright to me - so guess it might have something to do with other parameters. Can you post the complete config?

**Comment by lutzfischer** [comment]
The only thing I see is, that the tolerances are a bit high. Do you need 10 and 25ppm? I have never looked at phox results personally - so can't give you any more details as such.
