### ISSUE TITLE
add modification by specify the position

### ISSUE THREAD

**Issue by ShadoWyyyy** [Rappsilber-Laboratory/XiSearch#77]
hello, I know the modifications are represent as follow:
modification:(fixed|variable|known)::SYMBOL:(how is the modification represented);MODIFIED:[amino acid];MASS:[mass of the modified amino acid]
for example Carbamidomethylation on cysteine are
modification:fixed::SYMBOLEXT:cm;MODIFIED:C;DELTAMASS:57.021464

if I have a modification on protein N term or peptide N term, regardless of what amino acids it is, what should i fill in the MODIFIED[amino acid], I can't just fill in all amino acids, because the main point is to show it's a modification on N term, appreciate any help.

**Comment by lutzfischer** [comment]
I know it's a closed issue but just in case somebody else stumbles over this - 
peptide nterminal modification:
>modification:fixed::SYMBOLEXT:cm;MODIFIED:X;DELTAMASS:57.021464;PEPTIDEPOSITION:nterm
 
Protein nterminal modification:
>modification:fixed::SYMBOLEXT:cm;MODIFIED:X;DELTAMASS:57.021464;PROTEINPOSITION:nterm

if  the X is replaced with a list of residues, only these will be modified if nterminal.

newer versions of xisearch also permit
>modification:fixed::SYMBOLEXT:cm;MODIFIED:C,nterm;DELTAMASS:57.021464

meaning C anywhere and anything on a protein nterminal (peptide would be pepnterm)
