### ISSUE TITLE
 Failed to write core dump

### ISSUE THREAD

**Issue by helloworld1631** [Rappsilber-Laboratory/XiSearch#82]
When my search came to 58%, it stopped and reported a fatal error - 

```
INFO: 58% processed (24273) 24378 read of 41620 Estimated remaining: 2hours 49minutes to 3hours 13minutes
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000066f0aa78, pid=19560, tid=0x0000000000006554
#
# JRE version: Java(TM) SE Runtime Environment (8.0_371) (build 1.8.0_371-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.371-b11 mixed mode windows-amd64 )
# Problematic frame:
# V  [jvm.dll+0x11aa78]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\CL_search_engine\xiSEARCH\xiSEARCH_1.7.6.7\hs_err_pid19560.log
```

Are there any problems with my Java setting? Or is that due to running out of memory(I assigned 32G memory)?

Thanks in advance for any help and suggestions.

**Comment by grandrea** [comment]
hello, this could be out of memory, yes. How many proteins do you have in the database? 
Could you post your config and the contents of the log file mentioned in the error message?

**Comment by helloworld1631** [comment]
Hi, I have ~7000 proteins in my database. If search against the whole proteome, e.g. 20k proteins, how much memory should I assign to it?
I tried again with 50 GB, but it still reported the same error. Attach the config and the log file in the link: [https://gtvault-my.sharepoint.com/:f:/g/personal/zwang3136_gatech_edu/En1f75HH81ZJqv2Y3slQlfMBy1zn3AcLB0kvjbIAkBp1TQ](url) .
Thank you!

**Comment by lutzfischer** [comment]
this actually does not look like memory problem. can you try with a different/newer java version?

**Comment by helloworld1631** [comment]
Thank you, it works. I changed from the newest version to 16.0.2
