### ISSUE TITLE
mzid file is not created after data processing

### ISSUE THREAD

**Issue by Ke-Pu** [Rappsilber-Laboratory/XiSearch#99]
[20240326 Error.txt](https://github.com/Rappsilber-Laboratory/XiSearch/files/14759245/20240326.Error.txt)

Dear Rappsilber lab,

I am Ke Pu from FMP Berlin. Recently I met an error message about xiSearch, it doesn't create mzid file after data processing, I have copied the error message for your information. Could you please help me to figure it out? Thanks.

Best regards
Pu Ke

**Comment by grandrea** [comment]
Hello,

is this from running FDR inside xiSEARCH or from running xiFDR as a standalone application?

This problem looks like the ExceptionInitializer bug. This is easily avoided adding a flag to the xiSEARCH or xiFDR launcher as described here https://github.com/Rappsilber-Laboratory/xiFDR?tab=readme-ov-file#mzidentml-output

**Comment by lutzfischer** [comment]
The problem is that newer version of java have some additional security restrictions. Do address these some additional parameters are needed when starting xiSEARCH. The newest version will restart themself with the needed parameters.
